### ISSUE TITLE
Perl version (5.26.1) issue with unescaped left brace

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#177]
As shown on your colleagues computer in Lahore, we get the Internal Server Error when we run SQL-Ledger on Perl version 5.26.1. and this is the error message in the apache log file:

Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\\end{ <-- HERE document}/ at /var/www/html/sql-ledger/SL/Form.pm line 752.
Compilation failed in require at /var/www/html/sql-ledger/bin/mozilla/login.pl line 17.
BEGIN failed--compilation aborted at /var/www/html/sql-ledger/bin/mozilla/login.pl line 17.
Compilation failed in require at /var/www/html/sql-ledger/login.pl line 119.
[Thu Feb 06 10:52:29.224661 2020] [cgid:error] [pid 6173:tid 140635373807360] [client 127.0.0.1:60512] End of script output before headers: login.pl

**Comment by sweitmann** [comment]
Thanks, Armaghan!

**Comment by ledger123** [comment]
I have changed the code a little bit regarding temporary file handling once Philipp pointed out an issue with the code changes with error "Could not close csv file".

The error was due to missing opening statement for the CSVFILE variable. But since we are using File::Temp now which not only gives us a unique file name but also opens it, I have removed CSVFILE file variable with this one. I had not done this initially in an attempt to make minimal changes but with Philipp question, it seems it is more confusing than helpful so made the change and updated code is pushed to git hub.

Changes were made in develop branch.
