### ISSUE TITLE
Add preliminary vat return and gobd export feature

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#198]
Hi Armaghan, 

As discussed over Slack it would be great if we could add these two features from sl-community code:

Preliminary vat report: https://github.com/sl-community/rmac/commit/92a0b9b992f67892c724297e3fbdfeadc977edf9

gobd export: https://github.com/sl-community/rmac/commit/a589d7d51f3c2bf5262d2a759ab915a1a53e6933

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Good evening. 

I have just moved latest code from rmac into rma version and pushed to github in 198_ branch. While running I am getting a few errors which seem to be due to data. Please check it at your convenience and confirm it works on your test server in same way as rmac runs on that server.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

As discussed on slack regarding ip_whitelist

ip_whitelist variable in sql-ledger.conf contains ip address for which sql-ledger skips session cookie check if the request is coming from that ip address. This session cookie check is done in gateway pl files in the root sql-ledger folder in 'sub checkpassword'.

There is code similar to 'sub checkpassword' in the mojolicious code in mojo/lib/SL.pm in the 'sub logged_in' procedure. I have modified that procedure too so that it skips session cookie validation when request comes from the white listed ip address.

Also note that in change in $ip_whitelist variable in sql-ledger.conf also needs to be done in mojo/lib/SL.pm whenever it happens.

So we will not get 'Not logged in' when using ip_whitelist feature.

Hope I am able to clearly explain this issue. Kindly test at your convenience and confirm it works as intended.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

We have already fixed this ip_whitelist issue. If there is still anything to be done, please update this ticket.

Regards
