### ISSUE TITLE
Verify Checkbox in GL Transaction

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#220]
Hi Armaghan, 

Could you please add a small 'Verify' checkbox somewhere at the top in the General Transaction screen and make it searchable in 'General Ledger--Search'?

![Bildschirmfoto 2020-09-30 um 11 20 04](https://user-images.githubusercontent.com/100664/94667426-17958600-030f-11eb-86c0-b25176d326bc.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

As was discussed on slack on changing verify to onhold, I have done the changed and pushed code. Now you can mark any gl transaction as 'onhold'. GL search for 'onhold' will not only GL transactions but also ar or ap if any.

You need to add onhold column to 3 tables which you can using sql/Pg-custom_tables.sql.

Please test in your convenience and I shall write db upgrade script after everything is working so that databases get updated in the started way with this new onhold column.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Tested and it's perfect. You have done it again. Thank you for your excellent support.

Closing this ticket now. 

Regards
