### ISSUE TITLE
Data Export - Space after value

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#228]
Hi Armaghan, 

In order not to loose track of this issue (as posted on Slack on October 22nd) I'm also posting it here: 

a.) Most exports (e.g. AR open positions) have a space after the value. This applies for csv exports as well as copy pasting browser contents. This makes work difficult if you use the exported data in an excel sheet. Please cut out all spaces after the value.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Very surprising I cannot reproduce this at my end. AR/AP outstanding copy/pasting is working perfectly at my end as well as export as csv. Also I have checked trial balance, journal and drill down and all seem ok on our test server.

But I remember I had seen this space issue myself somewhere. Since you use it extensively with Excel, you will know exactly where or how it happens. 

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Please try running 'AR--Reports--Transactions' with marked 'CSV-Checkbox'. This will create a CSV-file. When you open this file in Libre Office of Excel you will see that there is an empty space after each value:

![Bildschirmfoto 2021-05-14 um 11 40 13](https://user-images.githubusercontent.com/100664/118252715-5c8ab900-b4a9-11eb-9e61-1a257daabc54.png)

**Comment by ledger123** [comment]
Hi Sebastian,

I have removed space in ar/ap/gl reports. Kindly test in your convenience.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Tested and it works beautifully. Thanks a million. 

Please release to develop. Closing this ticket now. 

Regards
