### ISSUE TITLE
VAT-Tax rates

### ISSUE THREAD

**Issue by raphaelroos** [ledger123/runmyaccounts#405]
Add a column vatkey in the tax table.
The column should be of type char(5).
 
Add a column formdigit in the tax table.
The column should be of type number.

Add a column validFrom in the tax table.
The column should be of type date.

The IBP team need to be able to read and write these columns via SQL-Ledger
[https://infoniqa.atlassian.net/wiki/spaces/PDCH/pages/327090323/SQL-Ledger+Dependencies#VAT-Tax-rates---to-do-by-sql-ledger-team](url)

**Comment by ledger123** [comment]
These columns are also added.

For both 404 and 405 changes, you need to run this sql on the database. 

ALTER TABLE chart ADD curr VARCHAR(3);
ALTER TABLE tax ADD vatkey VARCHAR(5);
ALTER TABLE tax ADD formdigit NUMERIC(12,2) DEFAULT 0;
ALTER TABLE tax ADD validfrom DATE;

Once all testing is done, I shall convert these sql statements into upgrade script in sql folder.

Please also note that this fix for Taxes management does not seem to be merged in develop. It is important to merge before testing so that this screen works correctly:

https://github.com/ledger123/runmyaccounts/issues/397

Here is screenshot of changes with new column:

![image](https://github.com/ledger123/runmyaccounts/assets/13597/6a944f74-5f10-43ea-84c4-883b43dec5a9)

**Comment by ledger123** [comment]
Hi,

Upgrade script also added for both tickets and commit is attached to this ticket above.

Regards

**Comment by ledger123** [comment]
Hi,

If all is ok, you can close this ticket.

Regards
