### ISSUE TITLE
Chart_id in acc_trans should not accept NULL

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#42]
Hi Armaghan,

as discussed in our Skype call today, Chart_id in acc_trans should not be allowed to be NULL.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have added to to sql/Pg-tables.sql so that new databases will contain this statement.

For existing databases, following statement needs to be run on each database.

    alter table acc_trans alter column chart_id set not null;

If table already contains null values then those rows either need to be deleted or set to zero with something like:

   update acc_trans set chart_id = 0 where chart_id is null;

and to delete

   delete * from acc_trans where chart_id is null;

Regards

**Comment by sweitmann** [comment]
As discussed in Lahore: We should add a general feature that checks the database version at login and updates it if necessary.
