### ISSUE TITLE
[IBP-573] - [LineTax / SQL-Ledger] - VAT-Codes without Reverse charge ignored in the bookings 

### ISSUE THREAD

**Issue by MariaHashimi** [ledger123/runmyaccounts#434]
If we have normal codes and codes linked to a reverse charge in a booking, the normal codes are just ignored by SQL-Ledger in the calculations and the booking.
Nothing is booked on those accounts (normal VAT Codes)

VAT config:
![image](https://github.com/ledger123/runmyaccounts/assets/116798460/2cfc022f-0c9e-4177-a275-0f577c517730)

Booking:
![image](https://github.com/ledger123/runmyaccounts/assets/116798460/474d5988-ea13-4303-be20-4fc331f632a2)

Journal:
![image](https://github.com/ledger123/runmyaccounts/assets/116798460/3efbc289-5512-4781-b08a-63317b691dd0)

As you can see in the journal, nothing is booked on account 11730.

**Comment by MariaHashimi** [comment]
Hi @ledger123,
You will find the recording of this issue attached to this comment

https://github.com/ledger123/runmyaccounts/assets/152606672/dbb153ae-dd62-448b-8aac-afc1841c33a2

**Comment by MariaHashimi** [comment]
Hi @ledger123,

We discussed this with the accountants this afternoon, and they explained that this form of booking (mix of normal bookings and reverse charge) was quite often used (credit card statement, revolute, salary declaration where the employee charges back the expenses, etc).

So would it be possible for you to implement this? Allowing the mixing of normal VAT and RC in the same booking.

We remain at your disposal for any further questions you may have,

Seee you,
Maria

**Comment by ledger123** [comment]
Hi @MariaHashimi ,

This has been fixed in the ticket specific branch as you can see from following screen shots. Testing can be done on my server or your own environment and let me know if there is any issue.

Regards

![image](https://github.com/ledger123/runmyaccounts/assets/13597/a19c63db-4e29-4bcf-930d-f6de8aa7673c)

![image](https://github.com/ledger123/runmyaccounts/assets/13597/2e1400a4-f964-444f-8a7e-115d8b56e23b)

**Comment by MariaHashimi** [comment]
Successfully tested on your server, will close the issue :)
