### ISSUE TITLE
Review and fix 'Cash--Payment/ Payments' feature

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#45]
Hi Armghan,

These features need to be reviewed, also in regard to the fxamount and fxpaid data fields. Let look at it together next week.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Does this feature needs further work or discussion. Last time we saw this and it was working fine.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

This issue still exists. 

1.) On app.myledger.net goto 'Cash--Payments' and click on "Update". You will see the following invoices:

<img width="954" alt="bildschirmfoto 2016-06-06 um 17 57 08" src="https://cloud.githubusercontent.com/assets/100664/15828569/2d3420dc-2c10-11e6-9b74-06b99e5b36c5.png">

2.) Select the first one as above and click "Update". You will now see that next everything simply disappears:

<img width="999" alt="bildschirmfoto 2016-06-06 um 17 57 20" src="https://cloud.githubusercontent.com/assets/100664/15828621/581a6734-2c10-11e6-8e21-9c792ec239ac.png">

Regards
Sebastian

**Comment by ledger123** [comment]
Looks like this problem is caused by our change of adding fxamount and fxpaid columns. At one place we are using fxamount/fxpaid to find open invoices and at other we are using amount/paid columns.

So just a minor code change will fix this but only if fxamount/fxpaid contain values. Old databases which have not been updated with this will cause problem.

For single currency databases, these columsn can be updated like:

UPDATE ap SET fxamount = amount WHERE fxamount IS NULL;
UPDATE ap SET fxpaid = paid WHERE fxpaid IS NULL;

I have updated our online demo with the code and db statements.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, I ran the command you stated above on a local database which had this problem, but when I did I got the message that there were no entries that match the stated criteria. So I checked the content of the ap table in the database and then took the freedom to "adapt" your statement to:

UPDATE ap SET fxamount = amount WHERE fxamount = 0;
UPDATE ap SET fxpaid = paid WHERE fxpaid = 0;

And after that it worked. Could you please confirm that my "adapted" statement is also ok and that it won't harm the "zero transactions"? As you know, at RMA, AP and AR transactions are sometimes booked as "zero transactions" to keep track of documents related to the customer or vendor without affecting the accounting.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Correct. Your statements are better than what I had recommended. :)

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

we need to look into this again. 

Regards
