### ISSUE TITLE
Rounding Problem

### ISSUE THREAD

**Issue by benboehm** [ledger123/runmyaccounts#466]
There is a problem when creating bookings and rounding:
Before Posting:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/cba4f12e-c51b-424f-b197-667545b6586e)

After Posting:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/e46a859d-c8f4-47ce-a312-03e24ceef6fc)

And in the journal:
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/68f8f55f-a1f7-4823-8478-1805907eccdc)

**Comment by ledger123** [comment]
Problem here is that original line amount (39.90 in this case) is not saved in the database. Instead, it is stored as amount after deducting the inclusive tax amount and on transaction opening, it is recalculated again using tax percentage instead of taking the amount+tax from database and that is because sql-ledger cannot figure out which tax is for which amount if there are multiple lines. All is well in database if transaction is not edited. But if it needs to be edited, a corner case like this can cause rounding issue.

And reposting such a transaction multiple times will cause even more problem every time. 

Here is how it is stored in the database:

![MicrosoftTeams-image](https://github.com/ledger123/runmyaccounts/assets/13597/d18c1fee-8b2d-45c5-91d7-c61d2455f6da)

And here is code in bin/mozilla/aa.pl which is causing problem. I have tried to arrange it and also tried to use Math::Float to avoid rounding error but could not be fixed.

![MicrosoftTeams-image (1)](https://github.com/ledger123/runmyaccounts/assets/13597/3324bc08-766f-4f6b-871d-903253c7ba5b)

The only solution seems possible is to store the actual line amount in a new column in acc_trans and use it when we open such a transaction instead of recalculating with above code.

There is nothing wrong or tricky with adding a new column and minor code changes it will require. I just wanted to confirm if we should proceed this way or we can live with this corner case?

Please confirm and I shall proceed accordingly.

Regards

**Comment by benboehm** [comment]
Hey @ledger123 sorry about the delayed answer, but yes you can proceed with the proposal

thank you very much

**Comment by ledger123** [comment]
Hi @benboehm 

Good morning.

This issue is fixed as we had planned and commit is attached to this ticket.

You can test it now on our combined demo server or in your own environment.

Regards

**Comment by benboehm** [comment]
Hey @ledger123 

So testing this following issues occured

When creating an ap booking (only thing i tested, gl and ar could have similar issues) the values ended up being negativ

so if I create an ap booking with 39.90 as total, it will end up as -39.90

secondly, updating a gl booking doesnt work

**Comment by benboehm** [comment]
Hey @ledger123 on your system I cannot reproduce the issues I have on our system

However there still seems to be something off

I created `Test 1234` and `Test 1234 2`

both with amount 39.90 and taxamount 6.93

Difference is one is tax included, the other one not

But still both bookings look different from what I created

can you check and verify?

Thank you

**Comment by ledger123** [comment]
Hi @benboehm ,

It will be great if you can also share what you created as you are saying these transactions are different from what you created so your original contents will help to trouble shoot. Or if you prefer you can make a little screen cast of how you add the transaction and how it gets changed.

Of if you prefer, I am available for an online session any time with few minutes advance notice.

In my testing all is ok as I store original amount in the database and retrieve that amount instead of any reverse calculations.

Regards

**Comment by benboehm** [comment]
I created the same ones as the first one I created

So this: 
![image](https://github.com/ledger123/runmyaccounts/assets/56029764/9c694c51-1b82-42c1-8ee4-2d89232921d5)


one with tax included, one with tax excluded

**Comment by ledger123** [comment]
Hi @benboehm ,

I am unable to reproduce the issue on our test server. I have created a screen cast with my testing. Can you please check and confirm what I am missing? Or if you can create a little screen recording reproducing the issue and attach to this ticket or email me to understand how it is not working.

Regards

https://github.com/ledger123/runmyaccounts/assets/13597/f8576dfe-a24a-4409-9f82-01fcc4ce4398

**Comment by prufrma** [comment]
@ledger123 : Hey Armaghan :) Please find attached a video on how to reproduce the issue on your server.

https://github.com/ledger123/runmyaccounts/assets/117820271/d85787d1-8e53-478f-a76c-fa6c994e2b53

**Comment by prufrma** [comment]
![image](https://github.com/ledger123/runmyaccounts/assets/117820271/8dccbb0b-ed48-46b7-8f07-72266a682f88)

Issue still there. See video attached.

https://github.com/ledger123/runmyaccounts/assets/117820271/a8fadea1-d305-407b-bdbe-f983937d4df0

**Comment by ledger123** [comment]
Hi, Lets have teams meeting/interactive session whenever you like. I am available today and tomorrow. You can send me meeting link.

Regards

**Comment by prufrma** [comment]
Invite for meeting sent.

**Comment by prufrma** [comment]
Tested again on this branch successfully:

![image](https://github.com/ledger123/runmyaccounts/assets/117820271/b7d07f40-a344-4962-81d5-3247adb429ec)
