### ISSUE TITLE
#39137: Remove "Print and Post" buttons by config setting

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#7]
https://github.com/ledger123/ledger123/issues/11

**Comment by ledger123** [comment]
Hi Sebastian,

This has bee fixed.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

tested and keep having some issues:

1.) I prepare the invoice using "AR--Sales Invoice"

![bildschirmfoto 2016-04-12 um 14 38 55](https://cloud.githubusercontent.com/assets/100664/14460214/9798e928-00bc-11e6-9f38-310bfa9c12b9.png)

2.) And when I click "Print and Post" I get the following screen

![bildschirmfoto 2016-04-12 um 14 39 09](https://cloud.githubusercontent.com/assets/100664/14460282/fcd76e04-00bc-11e6-9f34-007806ca8915.png)

Any ideas?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

It took about 2 days and I have made changes so that print to pdf to screen will work. Unfortunate this fix still has following problems:

1. Since screen is not refreshed, invnumber and id remain blank which means subsequent 'print-and-post' click will save another invoice.

2. It is not even possible to show a different screen (like new invoice) since we can generate only one output stream to the browser which is pdf during this operation.

This problem is only for adding a new invoice. When editing an existing invoice, print and post can be run without worrying about duplicates but screen still stays there after this button is clicked.

I have tried many things to update the screen with invoice number and id using jquery/ajax but the invnumber fetched by ajax is not visible in post procedure since it is generated *after* submit.

The only other possibility seems to be rewriting the complete invoice form with ajax/jquery/websockets which becomes a big project in itself.

If there is still some technical way or workflow suggestion to do it which I am missing then please share and we can try that.

Regards

**Comment by nsamuelsson** [comment]
Hi Armaghan

I do not see such a problem. - Post the invoice and reply with pdf. Doesn't that work?

Kind regards
Nils

**Comment by ledger123** [comment]
Hi Nils,

Let me explain:

On web, we have one response for each request. In that response we decide what to send. It can be either a webpage (new invoice, updatated invoice), pdf or any other type of content. So when one type of response (http headers) is generated other cannot be. At least this is how I understand.

So due to this we cannot generate pdf invoice as well as update invoice screen as part of response to our one click of the button. Please correct / guide if I am wrong or missing something or today  is the day to learn something new. :)

The other possibility which just came to my mind is to generate a popup window with the pdf invoice and in the main window we do whatever we like, like showing add new invoice or updating invoice etc.

What you suggest?

Regards

**Comment by nsamuelsson** [comment]
Hi Armaghan

I do understand. On the http protocol level, my proposal looks like this:

**Request**:

POST /ar.pl HTTP/1.0
Content-Type: application/x-www-form-urlencoded

action=postandprint&...


**Response:**

HTTP/1.1 200 A cool pdf
Some header: ...

%PDF-1.3
%<C4><E5><F2><E5><EB><A7><F3><A0><D0><C4><C6>
4 0 obj
<< /Length
...



It only replies with a pdf, we do not have to show the invoice page!

Kind regards
Nils

**Comment by ledger123** [comment]
Hi Nils,

This is already happening with my changes in 007_ branch and generated PDF invoice is successfully downloaded in the browser.

The problem is that the new invoice which was created and where we had pressed this 'post and print' stays the same. Which means it does not have invoice number and invoice id even when a number and id have been generated in the database  during 'print and post'. The problem we are facing is updating THIS screen with the generated invoice number and id.

This is not a problem if user understand this and does not click 'Print and post' and just clicks 'Add new invoice' to add a new invoice. 

But if the user does click 'print and post' again, this invoice will be posted as a new invoice again and so on.

What I am unable to do is populate the invoice screen with invoice number and id when 'print and post' is clicked.

Is it so or I am missing something?

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have added the code to enable / disable print button from sql-ledger.conf. 

It seems that Nils had already removed the button but we can add it back and disable with this change.

Regards
