### ISSUE TITLE
#34712: Template selection possibility in 'Batch--Email--...'

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#8]
https://github.com/ledger123/ledger123/issues/18

**Comment by ledger123** [comment]
Hi Sebastian,

I started working on this ticket and then I realized why we need it? Every possible template usage is listed as a separate menu option under Batch--Email. 

For example instead of selecting Invoice, Packing List or Pick List from Email screen, you can select these 3 type of templates individually from Batch--Email. Same is the case with Orders.

We can discuss it on slack. May be I am not getting it right.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have added language selection to the template selection. Hope this closes this issue.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested. Looking good. But as it works now it always email the language template that was selected when the invoice was booked. So, it doesn't matter what I select using the template selection. 

Would it be possible to change this, so that the language selected prior to sending the batch emails prevail?

Regards
